apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fz4aollr6-python 
  janus-idp.io/tekton: fz4aollr6-python
  backstage.io/kubernetes-id: fz4aollr6-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fz4aollr6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml