apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fz4aollr6-python
  janus-idp.io/tekton: fz4aollr6-python
  backstage.io/kubernetes-id: fz4aollr6-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fz4aollr6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
